#:kivy 2.3.1

#:set tool_bar_height 150
#:set floor_height 150
#:set greenhouse_height 1370

<HomeScreen>:
    canvas:
        # White Base Layer
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            pos: 0, 0
            size: self.width, self.height

        # Blue Sky
        Color: 
            rgba: 0, 0.15, 1, 0.3
        Rectangle:
            pos: 0, floor_height + tool_bar_height
            size: self.width, self.height

        # Sun Rays
        #Color:
        #    rgba: 0.84, 0.75, 0.7, 0.7
        #Quad:
        #    points: 
        #        [self.width-70-30, self.height-40-20,
        #        self.width-70-300, self.height-40-1500,
        #        self.width-70+0, self.height-40-1500,
        #        self.width-70+30, self.height-40-20]
        #Quad:
        #    points: 
        #        [self.width-90-30, self.height-40-20,
        #        self.width-90-1000, self.height-40-1500,
        #        self.width-90-700, self.height-40-1500,
        #        self.width-90+30, self.height-40-20]
        #Quad:
        #    points: 
        #        [self.width-120-30, self.height-10-20,
        #        self.width-120-1500, self.height-10-1200,
        #        self.width-120-1100, self.height-40-1200,
        #        self.width-120+30, self.height-40-20]
        
        # Bottom Tool Bar
        Color:
            rgba: 0.3, 0.18, 0.1, 1
        Rectangle:
            pos: 0, 0
            size: self.width, tool_bar_height
        Color:
            rgba: 0, 0, 0, 1
        Line:
            points: 0, tool_bar_height, self.width, tool_bar_height
            width: 12
        
    # GreenHouse
    Image:
        size_hint: None, None
        size: self.texture_size
        id: greenhouse
        source: f"greenhouse/greenhouse.png"
        pos: 0, floor_height
        width: root.width
        height: self.width / self.image_ratio

    # Sun
    Image:
        size_hint: None, None
        size: self.texture_size
        id: sun
        source: f"greenhouse/sun.png"
        pos: root.width*2/3, -180 + greenhouse_height + tool_bar_height + floor_height
        width: root.width - 470
        height: self.width / self.image_ratio
        opacity: 0.6

    # Top GreenHouse Bar
    Image:
        size_hint: None, None
        size: self.texture_size
        id: top_bar
        source: f"greenhouse/top_bar.png"
        pos: 0, root.height - 90
        width: root.width
        height: self.width / self.image_ratio
        opacity: 1

    # Shelves
    Image:
        id: shelving
        source: "greenhouse/shelving.png"
        size_hint: None, None
        width: root.width - 40
        height: self.width / self.image_ratio
        pos: 20, floor_height + tool_bar_height - 120

    # Plants Layer
    FloatLayout:
        id: plant_layer
        size_hint: None, None
        size: root.size
        pos: 0, 0

    # Currency
    Label:
        size_hint: None, None
        size: self.texture_size
        font_size: 57
        right: root.width - 10
        top: root.height + 10
        text: "{} Vit.".format(app.local_data.vitality)
        color: 0.2, 0.6, 0.2, 1
        font_name: 'PixelifySans'

    # Time
    Label:
        size_hint: None, None
        size: self.texture_size
        font_size: 57
        x: root.x + 10
        top: root.height + 5
        text: f"4:30"
        color: 0.2, 0.6, 0.2, 1
        font_name: 'PixelifySans'

# Plant Widget Template
<PlantWidget>:
    size_hint: None, None
    size: self.texture_size 
    y: 20 + floor_height + tool_bar_height
    x: (100 + self.plant.data.get('x', 0) * 150 if self.plant else 0) - self.width / 2